blueprint:
  name: deCONZ - IKEA five button remote for lights
  description: 'Control lights with an IKEA five button remote (the round ones).


    The middle "on" button, toggle the lights on/off to the last set brightness (unless the force brightness is toggled on in the blueprint).

    Dim up/down buttons will change the brightness smoothly and can be pressed and hold until the brightness is satisfactory.

    The "left" and "right" buttons can be assigned to an short and long button press action. This allows you to assign, e.g., a scene or anything else.
    '
  domain: automation
  input:
    remote:
      name: Remote
      description: IKEA remote to use
      selector:
        device:
          integration: deconz
          manufacturer: IKEA of Sweden
          model: TRADFRI remote control
    light:
      name: Light(s)
      description: The light(s) to control
      selector:
        target:
          entity:
            domain: light
    force_brightness:
      name: Force turn on brightness
      description:
        'Force the brightness to the set level below, when the "on" button
        on the remote is pushed and lights turn on.

        '
      default: false
      selector:
        boolean: {}
    brightness:
      name: Brightness
      description: Brightness of the light(s) when turning on
      default: 50
      selector:
        number:
          min: 0.0
          max: 100.0
          mode: slider
          step: 1.0
          unit_of_measurement: "%"
mode: restart
max_exceeded: silent
variables:
  force_brightness: !input "force_brightness"
  var_light: !input "light"
trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      device_id: !input "remote"
action:
  - variables:
      event: "{{ trigger.event.data.event }}"
  - choose:
      
      # Middle toggle button
      - conditions:
          - "{{ event == 1002 }}"
        sequence:
          - choose:
              - conditions:
                - "{{is_state(var_light, \"on\")}}"
                sequence:
                  - service: light.turn_off
                    target: !input "light"
                    data:
                      transition: 5
              
              - conditions:
                  - "{{is_state(var_light, \"off\")}}"
                sequence:
                  - choose:
                    - conditions: "{{ force_brightness }}"
                      sequence:
                        - service: light.turn_on
                          target: !input "light"
                          data:
                            transition: 0.5
                            brightness_pct: !input "brightness"
            default:
              - service: light.toggle
                target: !input "light"
                data:
                  transition: 0.5
      
      # Up short
      - conditions:
          - "{{ event == 2002 }}"
        sequence:
          - service: light.turn_on
            target: !input "light"
            data:
              brightness_step_pct: 10
              transition: 0.5
      # Up long
      - conditions:
          - "{{ event == 2001 }}"
        sequence:
          - repeat:
              count: 10
              sequence:
                - service: light.turn_on
                  target: !input "light"
                  data:
                    brightness_step_pct: 10
                    transition: 0.5
                - delay: 0.5
      
      # Down short
      - conditions:
          - "{{ event == 3002 }}"
        sequence:
          - service: light.turn_on
            target: !input "light"
            data:
              brightness_step_pct: -10
              transition: 0.5
      
      # Down long
      - conditions:
          - "{{ event == 3001 }}"
        sequence:
          - repeat:
              count: 10
              sequence:
                - service: light.turn_on
                  target: !input "light"
                  data:
                    brightness_step_pct: -10
                    transition: 0.5
                - delay: 0.5
      
      # Left short
      - conditions:
          - "{{ event == 4002 }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              color_mode: hs
              hs_color:
                - '{{ state_attr(var_light, "hs_color")[0] }}'
                - >-
                  {% if state_attr(var_light, "hs_color")[1] - 20 < 0 %}
                    {{ state_attr(var_light, "hs_color")[1] - 20 + 100 }}
                  {% else %}
                    {{ state_attr(var_light, "hs_color")[1] - 20 }}
                  {% endif %}
              transition: 0.5

      # Left long
      - conditions:
          - "{{ event == 4001 }}"
        sequence:
          - repeat:
              while: []
              sequence:
                - service: light.turn_on
                  target: !input light
                  data:
                    color_mode: hs
                    hs_color:
                      - '{{ state_attr(var_light, "hs_color")[0] }}'
                      - >-
                        {% if state_attr(var_light, "hs_color")[1] - 10 < 0 %}
                          {{ state_attr(var_light, "hs_color")[1] - 10 + 100 }}
                        {% else %}
                          {{ state_attr(var_light, "hs_color")[1] - 10 }}
                        {% endif %}
                    transition: 0.5
                - delay: 0.5
      
      # Right short
      - conditions:
          - "{{ event == 5002 }}"
        sequence:
          - service: light.turn_on
            target: !input "light"
            data:
              color_mode: hs
              hs_color:
                - >-
                  {% if state_attr(var_light, "hs_color")[0] + 18 > 360 %}
                    {{ state_attr(var_light, "hs_color")[0] + 18 - 360 }}
                  {% else %}
                    {{ state_attr(var_light, "hs_color")[0] + 18 }}
                  {% endif %}
                - '{{ state_attr(var_light, "hs_color")[1] }}'
              transition: 0.5

      #Right long
      - conditions:
          - "{{ event == 5001 }}"
        sequence:
          - repeat:
              while: []
              sequence:
                - service: light.turn_on
                  target: !input "light"
                  data:
                    color_mode: hs
                    hs_color:
                      - >-
                        {% if state_attr(var_light, "hs_color")[0] + 18 > 360 %}
                          {{ state_attr(var_light, "hs_color")[0] + 18 - 360 }}
                        {% else %}
                          {{ state_attr(var_light, "hs_color")[0] + 18 }}
                        {% endif %}
                      - '{{ state_attr(var_light, "hs_color")[1] }}'
                    transition: 0.5
                - delay: 0.5
    # Any other event will cancel the repeat loops.
    default: []
